install shell completions

diff --git a/src/bin/install b/src/bin/install
--- a/src/bin/install
+++ b/src/bin/install
@@ -1,17 +1,15 @@
-#!/bin/bash
-
 ################################################################################################
 #                                                                                              #
 # This script installs the latest release of defang from GitHub. It is designed                #
 # to be run like this:                                                                         #
 #                                                                                              #
-# . <(curl -Ls https://s.defang.io/install.sh)      #
+# . <(curl -Ls https://s.defang.io/install)                                                    #
 #                                                                                              #
 # This allows us to do some interactive stuff where we can prompt the user for input.          #
 #                                                                                              #
 ################################################################################################
 
-echo "
+echo "\
        __     ____
   ____/ /__  / __/___ _____  ____ _
  / __  / _ \/ /_/ __ \`/ __ \/ __ \`/
@@ -20,9 +18,9 @@ echo "
                           /____/
 "
 
-# Check for -y flag or CI var and set the REPLY variable to "y" if it is present
+# Check for -y flag or CI var and the REPLY variable to "y" if it is present
 if [[ "$1" == "-y" ]] || [[ "$CI" == "1" ]] || [[ "$CI" == "true" ]]; then
-    REPLY="y"
+    REPLY="y" # TODO: this will fail in Fish shell
     CI="1"
 fi
 
@@ -31,7 +29,7 @@ RELEASE_API_URL="https://api.github.com/repos/defang-io/defang/releases/latest"
 
 # Use curl to fetch the latest release data
 echo "Fetching the latest release information..."
-RELEASE_JSON=$(curl -s $RELEASE_API_URL)
+RELEASE_JSON=$(curl -s -L $RELEASE_API_URL)
 
 # Check for curl failure
 if [ $? -ne 0 ]; then
@@ -101,8 +99,7 @@ elif [ "$OS" = "Linux" ]; then
 fi
 
 # Determine the installation directory
-if [ -z "$INSTALL_DIR" ]
-then
+if [ -z "$INSTALL_DIR" ]; then
     INSTALL_DIR="$HOME/.local/bin"
 fi
 
@@ -134,15 +131,16 @@ if ! chmod +x "$INSTALL_DIR/$BINARY_NAME"; then
     return 10
 fi
 
-# Cleanup: Remove the temporary directory
-echo "Cleaning up..."
-rm -r "$EXTRACT_DIR"
-
-prompt_and_append_to_profile() {
+# Usage: _prompt_and_append_to_profile "Prompt string" "path/to/.rcfile" "line to add"
+_prompt_and_append_to_profile() {
     local prompt=$1
     local profile_file=$2
-    local line="export PATH=\"\$PATH:$INSTALL_DIR\""
-    echo "We'd like this line to your $profile_file:"
+    local line=$3
+    # Check with grep whether the line is already there
+    if grep -qF "$line" "$profile_file"; then
+        return
+    fi
+    echo "We'd like to append this line to your $profile_file:"
     echo
     echo "  $line"
     echo
@@ -158,7 +156,7 @@ prompt_and_append_to_profile() {
         echo "$line # Added by Defang install.sh" >> "$profile_file"
     else
         # Print the command for the user to run manually
-        echo "To add $INSTALL_DIR to your PATH, run the following command:"
+        echo "To manually add the required line, run the following command:"
         echo
         echo "  echo '$line' >> \"$profile_file\""
         echo
@@ -173,6 +171,9 @@ if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
     echo "Adding $INSTALL_DIR to your PATH for this session."
     export PATH="$PATH:$INSTALL_DIR"
 
+    echo "Adding $INSTALL_DIR to your PATH for future sessions."
+    EXPORT_PATH="export PATH=\"\$PATH:$INSTALL_DIR\""
+
     # Define the possible shell profile files
     PROFILE_FILES=(".bashrc" ".zshrc" ".kshrc")
 
@@ -182,27 +183,51 @@ if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
         # If the profile file exists in the user's home directory, add a line to it
         if [[ -f "$HOME/$profile_file" ]]; then
             FOUND_PROFILE_FILE=true
-            prompt_and_append_to_profile "Can we append the necessary line to" "$HOME/$profile_file"
+            _prompt_and_append_to_profile "Can we append the necessary line to" "$HOME/$profile_file" "$EXPORT_PATH"
         fi
     done
 
     # If no profile file was found
     if [[ $FOUND_PROFILE_FILE == false ]]; then
         # Prompt the user to create a new profile file
-        prompt_and_append_to_profile "No existing profile file found. Can we create" "$HOME/.${CURRENT_SHELL}rc"
+        CURRENT_RC="$HOME/.${CURRENT_SHELL}rc"
+        _prompt_and_append_to_profile "No existing profile file found. Can we create" "$CURRENT_RC" "$EXPORT_PATH"
     fi
 fi
 
-# TODO: Install shell completion script
+# Usage: _generate_completion_script "path/to/completion/_script"
+_generate_completion_script() {
+    local target=$1
+    echo "Generating completion script at $target"
+    mkdir -p "$(dirname "$target")"
+    defang completion $CURRENT_SHELL > "$target"
+}
 
+# Usage: _install_completion_script "shell"
+_install_completion_script() {
+    local shell=$1
+    local profile_file=".${shell}rc"
+    case $shell in
+        bash)
+            _generate_completion_script "$HOME/.local/share/bash-completion.d/defang" || return 11
+            _prompt_and_append_to_profile "Can we add shell completions to" "$HOME/$profile_file" "source \$HOME/.local/share/bash-completion.d/defang"
+            ;;
+        zsh)
+            _generate_completion_script "$HOME/.local/share/zsh/site-functions/_defang" || return 12
+            if [[ ":$FPATH:" != *":$HOME/.local/share/zsh/site_functions:"* ]]; then
+                _prompt_and_append_to_profile "Can we add shell completions to" "$HOME/$profile_file" "fpath=(\$HOME/.local/share/zsh/site-functions \$fpath)"
+            fi
+            ;;
+        *) return 13 ;;
+    esac
+}
 
-# Loop over the possible profile files
-for profile_file in "${PROFILE_FILES[@]}"; do
-    # If the profile file exists in the user's home directory, add a line to it
-    if [[ -f "$HOME/$profile_file" ]]; then
-        prompt_and_append_to_profile "Can we append the necessary line to" "$HOME/$profile_file"
-    fi
-done
+_install_completion_script $CURRENT_SHELL
+[[ $0 != $CURRENT_SHELL ]] && _install_completion_script $0
+
+# Cleanup: Remove the temporary directory
+echo "Cleaning up..."
+rm -r "$EXTRACT_DIR"
 
 # Cleanup: Remove the originally downloaded file
 rm "$FILENAME"
