reformat and add error message for bad version

diff --git a/src/bin/install b/src/bin/install
--- a/src/bin/install
+++ b/src/bin/install
@@ -26,18 +26,18 @@ fi
 
 # check if DEFANG_INSTALL_VERSION is set and set the release path accordingly
 if [[ -z "$DEFANG_INSTALL_VERSION" ]]; then
-    RELEASE_PATH="/latest"
+    RELEASE_PATH="latest"
 else
-    RELEASE_PATH="/tags/$DEFANG_INSTALL_VERSION"
+    RELEASE_PATH="tags/$DEFANG_INSTALL_VERSION"
 fi
 
-# Use curl to fetch the latest release data
-echo "Fetching the latest release information..."
-RELEASE_JSON=$(curl -s -L https://api.github.com/repos/DefangLabs/defang/releases$RELEASE_PATH)
+# Echo fetching the release path either latest or strip the tags/ from the version
+echo "Fetching the ${DEFANG_INSTALL_VERSION:-latest} release of defang..."
+RELEASE_JSON=$(curl -s -f -L https://api.github.com/repos/DefangLabs/defang/releases/$RELEASE_PATH)
 
 # Check for curl failure
-if [ $? -ne 0 ]; then
-    echo "Error fetching release information. Please check your connection or if the URL is correct."
+if [ -z "$RELEASE_JSON" ]; then
+    echo "Error fetching release information. Please check your connection or if the version is correct."
     return 1
 fi
 
@@ -80,7 +80,7 @@ elif [ "$OS" = "Linux" ]; then
 fi
 
 # Download the file
-if ! curl -s -L "$DOWNLOAD_URL" -o "$FILENAME"; then
+if ! curl -s -f -L "$DOWNLOAD_URL" -o "$FILENAME"; then
     echo "Download failed. Please check your internet connection and try again."
     return 4
 fi
